# Generated by Django 2.1 on 2019-01-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('NickName', models.TextField()),
                ('Email', models.EmailField(max_length=70)),
                ('Password', models.CharField(max_length=5)),
            ],
        ),
    ]
