# Generated by Django 2.1 on 2019-01-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DbApp', '0003_previousscans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='previousScans',
        ),
    ]
