# Generated by Django 2.1 on 2019-01-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbApp', '0005_previousscans'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AdminSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('NickName', models.TextField()),
                ('Email', models.EmailField(max_length=70)),
                ('Password', models.CharField(max_length=5)),
                ('Profession', models.CharField(max_length=5)),
            ],
        ),
    ]
