# Generated by Django 2.1 on 2019-04-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbApp', '0006_adminlogin_adminsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=70)),
                ('Message', models.CharField(max_length=250)),
            ],
        ),
    ]
